version: "3"

services:
  traefik:
    image: traefik:v2.0
    container_name: traefik
    ports:
      - "80:80" # <== http
      - "8080:8080" # <== :8080 is where the dashboard runs on
      - "443:443" # <== https
    command:
      #### These are the CLI commands that will configure Traefik and tell it how to work! ####
      ## API Settings - https://docs.traefik.io/operations/api/, endpoints - https://docs.traefik.io/operations/api/#endpoints ##
      - --api.insecure=true # <== Enabling insecure api, NOT RECOMMENDED FOR PRODUCTION
      - --api.dashboard=true # <== Enabling the dashboard to view services, middlewares, routers, etc...
      - --api.debug=true # <== Enabling additional endpoints for debugging and profiling
      ## Log Settings (options: ERROR, DEBUG, PANIC, FATAL, WARN, INFO) - https://docs.traefik.io/observability/logs/ ##
      - --log.level=DEBUG # <== Setting the level of the logs from traefik
      ## Provider Settings - https://docs.traefik.io/providers/docker/#provider-configuration ##
      - --providers.docker=true # <== Enabling docker as the provider for traefik
      - --providers.docker.exposedbydefault=false # <== Don't expose every container to traefik, only expose enabled ones
      - --providers.file.filename=/dynamic.yaml # <== Referring to a dynamic configuration file
      - --providers.docker.network=web # <== Operate on the docker network named web
      ## Entrypoints Settings - https://docs.traefik.io/routing/entrypoints/#configuration ##
      - --entrypoints.web.address=:80 # <== Defining an entrypoint for port :80 named web
      - --entrypoints.web-secured.address=:443 # <== Defining an entrypoint for https on port :443 named web-secured
      ## Certificate Settings (Let's Encrypt) -  https://docs.traefik.io/https/acme/#configuration-examples ##
      - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true # <== Enable TLS-ALPN-01 to generate and renew ACME certs
      - --certificatesresolvers.mytlschallenge.acme.email=buitattrung@gmail.com # <== Setting email for certs
      - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json # <== Defining acme file to store cert information
    volumes:
      - ./letsencrypt:/letsencrypt # <== Volume for certs (TLS)
      - /var/run/docker.sock:/var/run/docker.sock # <== Volume for docker admin
      - ./dynamic.yaml:/dynamic.yaml # <== Volume for dynamic conf file, **ref: line 27
    networks:
      - my_network # <== Placing traefik on the network named web, to access containers on this network
    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
      - "traefik.http.routers.api.rule=Host(`monitor.trungbt.tk`)" # <== Setting the domain for the dashboard
      - "traefik.http.routers.api.service=api@internal" # <== Enabling the api to be a service to access
  server:
    image: demo-traefik-api
    container_name: demo-traefik-api
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=my_network"
      - "traefik.http.routers.demo-api-web.rule=Host(`api.trungbt.tk`)"
      - "traefik.http.routers.demo-api-secured.rule=Host(`api.trungbt.tk`)"
      - "traefik.http.routers.demo-api-web.entrypoints=web"
      - "traefik.http.routers.demo-api-secured.entrypoints=web-secured"
      - "traefik.http.routers.demo-api-web.middlewares=redirect@file"
      - "traefik.http.routers.demo-api-secured.tls.certresolver=mytlschallenge"
      - "traefik.http.services.demo-api.loadbalancer.server.port=3000"
  client:
    image: demo-traefik-app
    container_name: demo-traefik-app
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_BASE_API=https://api.trungbt.tk
    networks:
      - my_network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=my_network"
      - "traefik.http.routers.demo-app-web.rule=Host(`trungbt.tk`)"
      - "traefik.http.routers.demo-app-secured.rule=Host(`trungbt.tk`)"
      - "traefik.http.routers.demo-app-web.entrypoints=web"
      - "traefik.http.routers.demo-app-secured.entrypoints=web-secured"
      - "traefik.http.routers.demo-app-web.middlewares=redirect@file"
      - "traefik.http.routers.demo-app-secured.tls.certresolver=mytlschallenge"
      - "traefik.http.services.demo-app.loadbalancer.server.port=80"

networks:
  my_network:
    driver: bridge
